import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const harmonySansScThin = localFont({
  src: './fonts/HarmonyOS_Sans_SC_Thin.ttf',
  display: 'swap',
  variable: '--font-harmony-sans-sc-thin',
});

const harmonySansScLight = localFont({
  src: './fonts/HarmonyOS_Sans_SC_Light.ttf',
  display: 'swap',
  variable: '--font-harmony-sans-sc-light',
});

const harmonySansScRegular = localFont({
  src: './fonts/HarmonyOS_Sans_SC_Regular.ttf',
  display: 'swap',
  variable: '--font-harmony-sans-sc-regular',
});

const harmonySansScMedium = localFont({
  src: './fonts/HarmonyOS_Sans_SC_Medium.ttf',
  display: 'swap',
  variable: '--font-harmony-sans-sc-medium',
});

const harmonySansScBold = localFont({
  src: './fonts/HarmonyOS_Sans_SC_Bold.ttf',
  display: 'swap',
  variable: '--font-harmony-sans-sc-bold',
});

const harmonySansScBlack = localFont({
  src: './fonts/HarmonyOS_Sans_SC_Black.ttf',
  display: 'swap',
  variable: '--font-harmony-sans-sc-black',
});

export const metadata: Metadata = {
  title: '网盘',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <body
        className={` ${harmonySansScThin.variable} ${harmonySansScLight.variable} ${harmonySansScRegular.variable} ${harmonySansScMedium.variable} ${harmonySansScBold.variable} ${harmonySansScBlack.variable} h-screen cursor-default bg-background font-sans-regular text-foreground`}
      >
        <div className="h-full overflow-hidden">{children}</div>
      </body>
    </html>
  );
}
